name: 'Test GitHub Action - Docker With'
description: 'Test GitHub Action with a docker image with arguments'
branding:
  icon: lock
  color: purple
inputs:
  argument1:
    description: 'Argument 1'
    required: false
  argument2:
    description: 'Argument 2'
    required: false
  additional_arguments:
    description: 'Additional arguments'
    required: false
  runner_context:
    description: 'internal (do not set): the "runner" context object in json'
    required: true
    default: ${{ toJSON(runner) }}
runs:
  using: 'composite'
  steps:
    - name: run
      id: run
      shell: bash
      run: |
        base_encoded="$(echo '${{ inputs.runner_context }}' | base64)"

        args=(${{ inputs.argument1 }})
        args+=(${{ inputs.argument2 }})
        args+=(${{ inputs.additional_arguments }})
        args+=("${base_encoded}")
        args+=('${{ inputs.runner_context }}')

        docker run ghcr.io/jeroenknoops/github-actions-docker-with:main "${args[@]}"

        echo "::set-output name=args::${args[@]}"

        function test_arg_count {
          echo "Number of args: $#"
        }

        test_arg_count "${args[@]}"
    - name: Test
      shell: bash
      run: |
        function test_arg_count {
          echo "Number of args: $#"
        }

        test_arg_count ${{ steps.run.outputs.args }}
    - name: Run via uses and outputs
      uses: docker://ghcr.io/jeroenknoops/github-actions-docker-with:main
      with:
        args: ${{ steps.run.outputs.args }}
