name: 'Test GitHub Action - Docker With'
description: 'Test GitHub Action with a docker image with arguments'
branding:
  icon: lock
  color: purple
inputs:
  argument1:
    description: 'Argument 1'
    required: false
  argument2:
    description: 'Argument 2'
    required: false
  additional_arguments:
    description: 'Additional arguments'
    required: false
runs:
  using: 'composite'
  steps:
    - name: run 
      shell: bash
      run: |
        args=('${{ inputs.argument1 }}')
        args+=('${{ inputs.argument2 }}')
        args+=('${{ inputs.additional_arguments }}')
        docker run ghcr.io/jeroenknoops/github-actions-docker-with:main ${args[*]} 
