name: Test this action 

on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: test action
        uses: JeroenKnoops/github-actions-docker-with@1f9b6e40b6bd8c4d5c7ed81f1c61d527c55c805e
        with:
          argument1: "argument1"
