name: Test this action 

on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: test action
        uses: JeroenKnoops/github-actions-docker-with@main
        with:
          argument1: "argument1"
          additional_arguments: "--additional_argument1 1 --additional_argument2 blurk" 
